<?php

$lang['privacy_statement'] 	= '
	<h2>Legal and privacy issues, please address queries to:</h2>
<address>Brain Host, LLC<br />3660 Center Rd Suite 363 <br />Brunswick, Ohio 44212</address>
<p>Effective Date: 02/01/2012</p>
<p>Your privacy is very important to us. Accordingly, we have developed this Policy in order for you to understand how Brain Host, LLC (€œBrain Host€)  collects, uses, communicates, transfers, and makes use of personal information collected on our site: www.brainhost.com. The following outlines our privacy policy.</p>
<p>Brian Host, LLC has been awarded TRUSTe\'s Privacy Seal signifying that this privacy policy and practices have been reviewed by TRUSTe for compliance with TRUSTe\'s program requirements including transparency, accountability and choice regarding the collection and use of your personal information.  TRUSTe\'s mission, as an independent third party, is to accelerate online trust among consumers and organizations globally through its leading privacy trustmark and innovative trust solutions. If you have questions or complaints regarding our privacy policy or practices, please contact us <a href="support@brainhost.com">support [@] brainhost.com</a>.   If you are not satisfied with our response you can contact TRUSTe here. The TRUSTe program covers only information that is collected through this Web site.</p>
<p>We will collect and use personal information solely with the objective of fulfilling those purposes specified by us and for other compatible purposes as outlined in this privacy policy, unless we obtain the consent of the individual concerned or as required by law and when we believe that disclosure is necessary to protect our rights and/or to comply with a judicial proceeding, court order, or legal process served on our Web site.</p>
<p>If BrainHost is involved in a merger, acquisition, or sale of all or a portion of its assets, you will be notified via email and/or a prominent notice on our Web site of any change in ownership or uses of your personal information, as well as any choices you may have regarding your personal information.</p>
<p>We may retain personal information as long as we feel is necessary in our discretion for the fulfillment of the purposes outlined in this policy or as necessary to comply with our legal obligations, resolve disputes, and enforce our agreements. If you wish to cancel your account or request that we no longer use your information to provide you services contact us at <a href="support@brainhost.com">support [@] brainhost.com</a>.</p>
<p>We will collect personal information such as name, email address, phone number, address, and billing information by lawful and fair means upon your consent to this privacy policy, which is indicated upon submission of this information to BrainHost. Personal data should be accurate, complete, and up to date.</p>
<p>We will collect and use personal information solely with the objective of fulfilling those purposes specified by us and for other compatible purposes, unless we obtain the consent of the individual concerned or as required by law. From time to time, we may use customer information for new, unanticipated uses not previously disclosed in our privacy notice. If our information practices change at some time in the future we will contact you before we use your data for these new purposes to notify you of the policy change and to provide you with the ability to opt out of these new uses.</p>
<p>Upon request we provide site visitors with access to all information [including proprietary information] that we maintain about them. Consumers can access this information by logging into their account and making the change within their account management center or by e-mailing us at <a href="support@brainhost.com">support [@] brainhost.com</a>.</p>
<p>We will protect personal information by reasonable security safeguards against loss or theft, as well as unauthorized access, disclosure, copying, use or modification. We always use industry-standard encryption technologies when transferring and receiving sensitive data exchanged with our site. No method of transmission over the Internet, or method of electronic storage, is 100% secure, however.  Therefore, we cannot guarantee its absolute security. If you have any questions about security on our Web site, you can contact us at <a href="support@brainhost.com">support [@] brainhost.com</a>.</p>
<p>With respect to cookies: We do not link the information we store in cookies to any personally identifiable information you submit while on our site.</p>
<p>We use both session ID cookies and persistent cookies. A session ID cookie expires when you close your browser. A persistent cookie remains on your hard drive for an extended period of time. You can remove persistent cookies by following directions provided in your Internet browser\'s "help" file. We use cookies to ensure that visitors are not repeatedly sent the same banner ads.</p>
<p>If you reject cookies, you may still use our site, but your ability to use some areas of our site, such as contests or surveys, will be limited.</p>
<p>The use of cookies by our partners, affiliates and service providers is not covered by our privacy statement.  We do not have access or control over these cookies. Our partners, affiliates, service providers use session ID cookies to deliver special offers, discounts, promotions and custom software.</p>
<p><span style="text-decoration: underline;">Clear Gifs</span></p>
<p>Our third party advertising partner employs a software technology called clear gifs (a.k.a. Web Beacons/Web Bugs), that help us better manage content on our site by informing us what content is effective.  Clear gifs are tiny graphics with a unique identifier, similar in function to cookies, and are used to track the online movements of Web users.  In contrast to cookies, which are stored on a user\'s computer hard drive, clear gifs are embedded invisibly on Web pages and are about the size of the period at the end of this sentence. We do not tie the information gathered by clear gifs to our customers\' personally identifiable information.</p>
<p><span style="text-decoration: underline;">Log Files</span></p>
<p>As is true of most Web sites, we gather certain information automatically and store it in log files.  This information includes internet protocol (IP) addresses, browser type, internet service provider (ISP), referring/exit pages, operating system, date/time stamp, and clickstream data.</p>
<p>We use this information, which does not identify individual users, to analyze trends, to administer the site, to track users\' movements around the site and to gather demographic information about our user base as a whole.</p>
<p>We will send you service-related announcements on rare occasions when it is necessary to do so.  For instance, if our service is temporarily suspended for maintenance, we might send you an email. If you do not want to receive email from us in the future, please let us know by contacting us at support [@] brainhost.com.</p>
<p><span style="text-decoration: underline;">Service Providers</span></p>
<p>We use other third parties such as a credit card processing company to bill you for services, an email service provider to send out emails on our behalf, a client services partner to provide account management tools and a live chat provider to assist you if you have questions while using our site or regarding your order, and trusted third party advertising partners to send you special offers and promotions that we feel may be of interest to you  You may receive these messages via phone, SMS, email or direct mail.  When you sign up for our services, we will share your personal information only as necessary for the third party to provide that service. If you do not wish to receive advertisements from our partners please contact us at <strong><a href="support@brainhost.com">support [@] brainhost.com</a> </strong>or you may unsubscribe from particular advertisements by clicking the unsubscribe link within the advertisement.</p>
<p><span style="text-decoration: underline;">Re-Targeted Advertising</span></p>
<p>Re-Targeted advertising uses information collected on an individual\'s web browsing behavior such as the pages they have visited or the searches they have made. This information is then used to display ads. The information collected is only linked to an anonymous cookie ID (alphanumeric number); it does not include any information that could be linked back to a particular person, such as their name, address or credit card number. The information used for targeted advertising either comes from Brain Host or through third party website publishers. If you would like to opt out of re-targeted advertising from Brain Host that occurs when visiting our third party advertising publishers, please <a href="http://preferences.truste.com/truste/" onclick="javascript:_gaq.push([\'_trackEvent\',\'outbound-article\',\'http://preferences.truste.com\']);">click here</a>. Please note this does not opt you out of being served advertising. You will continue to receive generic ads.</p>
<p><span style="text-decoration: underline;">Links to Other Sites</span></p>
<p>This Web site contains links to other sites that are not owned or controlled by Brain Host. Please be aware that we, Brain Host, are not responsible for the privacy practices of such other sites.</p>
<p>We encourage you to be aware when you leave our site and to read the privacy statements of each and every Web site that collects personally identifiable information.</p>
<p>This privacy statement applies only to information collected by this Web site.</p>
<p><span style="text-decoration: underline;">Public Forums</span></p>
<p>Our Web site offers publicly accessible blogs or community forums. You should be aware that any information you provide in these areas may be read, collected, and used by others who access them. To request removal of your personal information from our blog or community forum, contact us at support [@] brainhost.com. In some cases, we may not be able to remove your personal information, in which case we will let you know if we are unable to do so and why.</p>
<p>From time to time, we may use customer information for new, unanticipated uses not previously disclosed in our privacy notice. If our information practices change at some time in the future we will contact you before we use your data for these new purposes to notify you of the policy change and to provide you with the ability to opt out of these new uses. We encourage you to periodically review this page for the latest information on our privacy practices.</p>
<p>If you feel that this site is not following its stated information policy, you may contact us at <a href="support@brainhost.com"><strong>support [@] brainhost.com</strong></a>.</p>
';

$lang['tos'] 	= '
	<p><strong>I. ACCEPTANCE OF TERMS OF SERVICE</strong></p>
<p><strong></strong>A. As a precondition and requirement to use the services available via Brain Host.com, you, for yourself and for the company or other person(s), if any, you represent ("Subscriber" or "Subscribers", as applicable), hereby accept and agree to be legally bound by the Acceptable Use Policy (€œAUP€) and these Terms of Service ("Terms"). These Terms and AUP are effective immediately between the Subscriber and Brain Host dba BrainHost.com, its subsidiaries and affiliates ("Brain Host"). Each Subscriber is subject to these Terms and AUP, and by using Brain Host\'s services, network and/or systems (collectively the "Services"), Subscriber agrees to be legally bound by and subject to all terms and conditions contained in the AUP and these Terms, including as well all usage policies and other policies herein. To the extent not inconsistent therewith, these Terms and AUP are also incorporated into the individual service agreement, if any, of each Subscriber.</p>
<p>B. Subscriber represents and warrants that, if an individual, Subscriber is at least 18 years old and otherwise legally competent in all respects to, or, if an entity, Subscriber is a corporation, limited liability company, partnership, or other legal entity duly formed and in good standing, as applicable, and possesses all legal authority and power to accept and be bound by these Terms. Additionally, Subscriber represents and warrants that neither it, she, or he (as applicable), nor any entity it, she or he represents, is prohibited under any part of section 13 of these Terms from registering or signing up with or otherwise subscribing to or receiving any of the Services from Brain Host. Further, Subscriber represents and warrants all information provided by Subscriber to Brain Host has been and is complete, accurate, and current, and that Subscriber shall continue to provide complete, accurate and current information to Brain Host in connection with all registration or renewal processes and further agrees to update all such information as necessary to maintain complete, accurate and current information. Although subscribers of paid services offered through Brain Host must be at least 18 years of age and otherwise legally competent to accept and be legally bound by these Term, a parent or legal guardian of a minor may obtain an account on the minor\'s behalf, and by doing so, consents to such minor\'s use of the Services. Subscribing parents and legal guardians each for herself or himself, as applicable, accept and agree to be legally bound by these Terms, and assume full responsibility and liability associated with any failure of compliance with the Terms in connection with said minor\'s use of any of the Services.</p>
<p>C. Brain Host intends to provide the best possible web hosting service to each of its Subscribers. Brain Host is also dedicated to staying abreast of new and available technologies that will better serve our Subscribers. However, due to changing technologies, changing laws and the individual and collective needs of our Subscribers, Brain Host reserves the right, in its sole discretion, to change, modify, add or remove all or any part of these Terms at any time with or without notice.</p>
<p><strong><span style="text-decoration: underline;">D. Subscribers may view the most current version of these Terms at </span></strong><a href="http://www.brainhost.com/terms-of-service/" ><strong>http://www.brainhost.com/terms-of-service/</strong></a><strong><span style="text-decoration: underline;">. Any use of the Services by Subscriber, after changes, modifications, additions or deletions to these Terms are posted on the BrainHost.com website, shall constitute Subscriber\'s acceptance of all such changes, additions, modifications or deletions. If a Subscriber does not agree to any such alterations to these Terms, the Subscriber\'s sole and exclusive remedy is to cancel the Subscriber\'s account as set forth in Paragraph 3 below.</span></strong></p>
<p><strong></strong>E. Notwithstanding Brain Host\'s right to alter these Terms without prior notice, Brain Host may, within its sole discretion and as a courtesy to all affected Subscribers, make an effort to provide Subscribers with 7 days advanced notice of any alteration of these Terms if it appears to Brain Host, in its sole discretion, that said alteration may materially and adversely impact said Subscriber\'s use of the Services.</p>
<p>F. If Subscriber is registering a new domain name with Brain Host, or using or transferring a previously registered domain name in conjunction with Subscriber\'s use of the Services, Subscriber hereby acknowledges and agrees that Subscriber\'s use of the domain name is also subject to the policies of the Internet Corporation for Assigned Names and Numbers ("ICANN") and the Domain Registration Agreement located at <a href="http://api.fastdomain.com/terms.html" onclick="javascript:_gaq.push([\'_trackEvent\',\'outbound-article\',\'http://api.fastdomain.com\']);">http://api.fastdomain.com/terms.html</a> and has read the Registrant Rights and Responsibilities located at <a href="http://www.icann.org/en/registrars/registrant-rights-responsibilities-en.htm" onclick="javascript:_gaq.push([\'_trackEvent\',\'outbound-article\',\'http://www.icann.org\']);">http://www.icann.org/en/registrars/registrant-rights-responsibilities-en.htm</a>.</p>
<p><strong>II. TERM &#8211; PAYMENT &#8211; RENEWAL OF ACCOUNT AND OF DOMAIN</strong></p>
<p><strong></strong>A. Term of Service. The term of Subscriber\'s subscription to the Services commences upon Subscriber\'s acceptance of these Terms and terminates as set forth in Paragraphs 2.05 and 3.01.</p>
<p>B. Payment. Subscriber agrees to pay all applicable fees for Services in effect at the time of sign-up registration and/or renewal, subject to these Terms. Subscriber agrees to update and keep current all of Subscriber\'s billing information, email and all other contact information. It is the Subscriber\'s responsibility to verify that the information submitted is accurate to insure proper billing and continuity of services. Brain Host may use Merchant Updater Services to receive updated billing information from participating providers.</p>
<p>C. Automatic Renewal of Hosting Account. As a courtesy and not as an obligation (contractual or otherwise), fifteen (15) days prior to the expiration of Subscriber\'s Hosting Account or Domain(s) Brain Host will automatically renew Subscriber\'s Hosting Account by charging the applicable fee for the non-promotional rate to Subscriber\'s current method of payment on file. The initial term of this Agreement shall be as set forth in the Registration Form (the "Initial Term"). The Initial Term shall begin upon commencement of the Services to User, and after the Initial Term, this Agreement shall continue for successive periods (or renewal period) of equal length as the Initial Term or such other Term and price that shall be set forth in a notice to the customer at least 24 hours prior to the commencement of such successive period or renewal period. In the case of insufficient funds we will attempt to collect at a partial term quantity ( not changing your current term) to continue service as per contract. Additionally after the initial Term, you acknowledge, agree and authorize us to automatically bill and/or charge on your credit card for successive or renewal periods, unless terminated or cancelled by either party as provided in this section. The Initial Term and all successive renewal periods shall be referred to, collectively, as the "Term". Subscriber acknowledges and confirms that if the Subscriber pays for a hosting plan which qualifies for a Free Domain that the Subscriber will be provided with a digital domain registration voucher to be used for purchasing their Free Domain. The domain registration voucher is only applicable as long as the Subscriber maintains a qualifying hosting plan.</p>
<p>D. Automatic Renewal of Domain(s). As a courtesy and not as an obligation (contractual or otherwise), fifteen (15) days prior to the expiration of Subscriber\'s domain, if registered with Brain Host (or one of its Affiliates), or if transferred to and registered with Brain Host (or one of its Affiliates), Brain Host will automatically renew Subscriber\'s domain, by charging the applicable fee to Subscriber\'s current method of payment on file. Subscriber acknowledges and confirms that the obligation to renew his/her/its Domain(s) is solely and exclusively the responsibility of the Subscriber, and is not the obligation (contractual or otherwise) of Brain Host. Subscriber hereby releases Brain Host from any and all liability for failure for any reason to renew said Account or said Domain(s). Subscriber acknowledges that there may be many reasons why Brain Host is unable to renew said Account or Domain, including but not limited to inability of Brain Host, for any reason, to bill said renewal to Subscriber\'s method of payment on file, to contact or otherwise get response from Subscriber at the email address on file, or otherwise. Subscriber acknowledges that said Hosting Account and/or Domain, if not renewed, for whatever reason, will expire on the Account or Domain Expiration Date, as applicable. In the event that a Domain expires, Brain Host will hold the expired Domain for up to 30 days as a courtesy and not as an obligation (contractual or otherwise). 30 days after expiration, the Domain will be placed in Redemption. During the Redemption period the Domain will be inaccessible and unable to be registered elsewhere. In order to bring a Domain out of Redemption, Subscriber must pay a Redemption Fee, as well as a Renewal Fee for the current year. Domain registration vouchers cannot be applied toward the cost of Redemption. If the Domain is not redeemed within 74 days of expiration, it will be set to Pending Delete status by the domain registry. After the Pending Delete status expires, the Domain will be released for registration. During the Pending Delete period, the Domain will be inaccessible and unrecoverable.</p>
<p>E. Cancellation of Automatic Renewal of Account or Domain. Subscriber agrees to notify Brain Host of Subscriber\'s intent to cancel automatic renewal at least sixteen (16) business days prior to the account or domain expiration date, by directing Automatic Account Renewal Cancellation Notification and/or Automatic Domain Renewal Cancellation Notification to Brain Host, as applicable, by sending same via email to <a href="mailto:support@BrainHost.com">support@BrainHost.com</a>. This request must include the verification of ownership of the hosting account and/or domains, as determined by Brain Host. <strong><span style="text-decoration: underline;">NOTE:</span></strong> The only way to cancel your account as a whole, rather than individual domains, is by calling our billing team at 1-800-311-9418.</p>
<p>F. Authority. In the event Subscriber is a corporation, limited liability company, partnership, joint venture, other business entity or group of individuals, the person registering for or renewing Brain Host Services on behalf of Subscriber hereby certifies that he/she has the authority to and does hereby bind the corporation, limited liability company, partnership, joint venture or other individuals in this manner and in connection with Subscriber\'s acceptance of all other Terms set forth herein.</p>
<p><strong>III. REFUND POLICY</strong></p>
<p><strong></strong>A. Cancellations and Refunds. We offer you a 30 Day Money-Back Guarantee on all shared hosting plans. You will not be able to receive a refund of any kind after thirty days.</p>
<p>B. Methods of cancellation: The only way to cancel your account is by calling our bill team at 1-800-311-9418. In the event Subscriber issues a chargeback or reversal of charges without first following the above cancellation procedures, the Subscriber will be responsible for a $50.00 billing service fee. NOTE: if you sign up in GBP pound sterlings then the domain charge we incur is the USD equivalent of that amount.</p>
<p>C. Nonrefundable Fees: Fees paid by Subscriber in connection with setup fees, domain registration and the activated traffic package upgrade are nonrefundable.</p>
<p>D. Dedicated Servers cannot receive refund: The 30 day money back guarantee does not apply to dedicated servers and no refund will be honored.</p>
<p>BRAIN HOST AS RESELLER OR LICENSOR<br /> Brain Host is acting only as a reseller or licensor of certain services, hardware, software and equipment used in connection with the products and/or Services that were or are manufactured or provided by a third party ("Non-Brain Host Product"). Brain Host shall not be responsible for any changes in the Services that cause the Non-Brain Host Product to become obsolete, require modification or alteration, or otherwise affect the performance of the Services. Any malfunction or manufacturer\'s defects of Non-Brain Host Product either sold, licensed or provided by Brain Host to User or purchased directly by User used in connection with the Services will not be deemed a breach of Brain Host\'s obligations under this Agreement. Any rights or remedies User may have regarding the ownership, licensing, performance or compliance of Non-Brain Host Product are limited to those rights extended to User by the manufacturer of such Non-Brain Host Product. User is entitled to use any Non-Brain Host Product supplied by Brain Host only in connection with User\'s permitted use of the Services. User shall use its best efforts to protect and keep confidential all intellectual property provided by Brain Host to User through any Non-Brain Host Product and shall make no attempt to copy, alter, reverse engineer, or tamper with such intellectual property or to use it other than in connection with the Services. User shall not resell, transfer, export or re-export any Non-Brain Host Product, or any technical data derived therefrom, in violation of any applicable United States or foreign law.</p>
<p><strong>IV. CANCELLATION POLICY</strong></p>
<p>A. Brain Host may terminate this Agreement, without penalty,</p>
<p>if proper evidence exists that a customer was exceptionally rude or vulgar in communications with our staff.</p>
<p>if the Services are prohibited by applicable law, or become impractical or unfeasible for any technical, Terms of Service or regulatory reason, by giving User as much prior notice as reasonably practicable; or</p>
<p>immediately, if Brain Host determines that User\'s use of the Services, the Web site or the User Content violates any Brain Host term of service, including the AUP, or Privacy Policy. If Brain Host cancels this Agreement prior to the end of the Term for Your breach of this Agreement and related agreements, including the AUP or Privacy Policy or User\'s use of the Services disrupts our network, Brain Host shall not refund to You any fees paid in advance of such cancellation and You shall be obligated to pay all fees and charges accrued prior to the effectiveness of such cancellation; further, We may charge You 100% of all charges for all Services for each month remaining in the then-current Term and Brain Host shall have the right to charge You an administrative fee of a minimum of $35.00.</p>
<p>B. Upon termination of this Agreement for any cause or reason whatsoever, neither party shall have any further rights or obligations under this Agreement, except as expressly set forth herein. Notwithstanding the expiration or termination of this Agreement, the parties shall each remain liable to the other for any indebtedness or other liability theretofore arising under this Agreement. Termination of this Agreement and retention of pre-paid fees and charges shall be in addition to, and not be in lieu of, any other Terms of Service or equitable rights or remedies to which Brain Host may be entitled.</p>
<p><strong>V. PROPRIETARY RIGHTS</strong></p>
<p>A. These Terms do not give Subscriber any rights in Brain Host intellectual property or technology. Brain Host and related trademarks and logos are the exclusive property of Brain Host. Brain Host and Subscriber agree that neither will, directly or indirectly, reverse engineer or decompile object code or execution code, nor otherwise seek to obtain source code or trade secrets of the other party. Notwithstanding the foregoing, nothing herein shall bar Brain Host from using any knowledge, information or skills that are generally known or that can be learned or otherwise acquired in the normal course of business.</p>
<p><strong>VI. SECURITY AND OWNERSHIP </strong></p>
<p>A. Site Security and Updates. Brain Host uses sophisticated means of security in connection with the Services. Notwithstanding the foregoing, it is exclusively Subscriber\'s obligation to maintain and control passwords to Subscriber\'s web site(s), and Subscriber exclusively is responsible for all activities that occur in connection with Subscriber\'s user name, password, and registered domain name(s), as well as any and all scripts or programs added to the account by the Subscriber or authorized users. Subscriber agrees to immediately notify Brain Host of any unauthorized uses of the Service or any other breaches of security. It is exclusively Subscriber\'s responsibility to update and secure any programs or scripts available via the cPanel interface. Subscriber\'s failure to update and secure any programs or scripts available via the cPanel interface may result in Brain Host either updating the programs and scripts or suspending your account services until they are updated. Brain Host will not be liable for any loss or damages of any kind, under any legal theory, caused by Subscriber\'s failure to comply with any of the foregoing security obligations or caused by any person to whom Subscriber grants access to Subscriber\'s Services, or due to any updates performed by Brain Host pursuant to the terms of this section.</p>
<p>B. Access and Control Policy. When a new account or domain, as applicable, is registered with or transferred to Brain Host or with one of its affiliates, the process requires and results in the creation of the following within the records of Brain Host, in association with said new account or domain: i) Name of person registering; ii) email address; iii) user name; iv) password; and, v) associated payment information, such as Visa, Mastercard, etc., Credit Card Number &amp; name thereon, etc.</p>
<p>If a person contacts Brain Host and claims that he or she is entitled to access to an account, website, or domain registered with Brain Host or its affiliate but is without access (for any reason such as but not limited to forgotten password or forgotten user name, data loss or corruption on personal computer, improperly locked out, and so forth), Brain Host will give access to the person who acceptably evidences he or she has substantially all of: i) name of the person who originally registered; ii) email address of the person who originally registered; iii) the user name of the person who originally registered, if possible; iv) the associated payment information of the person who registered, such as Visa, Mastercard, etc., Credit Card Number &amp; name thereon, etc. (mandatory); and, v) a photo identification evidencing she or he is the rightful possessor and user of said credit card or payment medium (mandatory). Otherwise, Brain Host will not give access and control to a claimant unless Brain Host is served with a valid order of a court, agency, or appropriate Internet controlling entity such as Internet Corporation for Assigned Names and Numbers ("ICANN"), requiring Brain Host to give such access and control to said claimant or unless there is submitted to Brain Host at legal@BrainHost.com a written statement duly signed by the person who originally registered said account which statement is duly notarized, and in which said originally registering person confirms that said claimant is entitled to access and control of the account, together with a written notarized statement duly signed by claimant which confirms claimant is entitled to access and control of said account, website and/or domain and has read and agreed to these Terms of Service. Subscriber acknowledges and accepts that the foregoing access and control policies and procedures are the only way that notice(s) can be given and changes can be effected regarding said access and/or control; and, further, that any other changes made directly by Subscriber or by others within the online records of Brain Host or of its affiliates shall not be deemed effective to give notice to Brain Host or its affiliates of any changes in said access or control.</p>
<p>Subscriber acknowledges and accepts said access and control policy and procedure, agrees not to bring any claim in the form of a lawsuit or otherwise against Brain Host arising out of its following said policy and procedure, agrees immediately to dismiss any claim so brought, and hereby releases Brain Host from all liability and all claims for damages or any other liability whatsoever that may arise out of Brain Host\'s following said policy and procedure.</p>
<p>C. License to Brain Host. Brain Host claims no ownership interest in the content of Subscriber\'s web site(s). By submitting content and data to Brain Host, Subscriber grants to Brain Host, its successors and assigns, the worldwide, royalty-free, and nonexclusive license under Subscriber\'s copyrights and other rights, if any, in all material and content displayed in Subscriber\'s web site to use, distribute, display, reproduce, and create derivative works from such material in any and all media, in order to maintain such content on Brain Host\'s servers during the term of these Terms. Subscriber also authorizes the downloading and printing of such material, or any portion thereof, by end-users for their personal use. This license shall terminate upon Subscriber\'s cancellation of the Services as set forth in Paragraphs 2.01 and 3.0.</p>
<p>D. Transfer of Ownership. Brain Host is not responsible to determine ownership of websites hosted by, accounts opened with, or domains registered with Brain Host or its affiliates. By accessing Brain Host\'s system, registering, or using any of the services provided by Brain Host, the Subscriber, or any other person so accessing, registering or using, hereby represents and warrants that the information provided in connection with said registration, including as well information concerning ownership of websites, domains, and accounts, is true, accurate, and complete in each material detail. Any disputes arising regarding the ownership of any account, website, or domain hosted by, opened with, or registered with Brain Host or any of its affiliates are subject to the terms and conditions of Section 5.5 of these Terms.</p>
<p>Brain Host will recognize a change of ownership of account(s) with, of websites hosted by, and/or of domains registered with Brain Host or its affiliates only in the event that at least one of the following occur: i) there is received by the Compliance Manager (tos@BrainHost.com) a written statement (in a form acceptable to Brain Host or applicable affiliate) containing the notarized signature of the original owner of the account, website, and/or domain, as applicable, confirming that ownership of the website, domain, and/or account, as applicable, has been transferred to a person (claimant) claiming to own said website, domain and/or account, as applicable, along with a written statement containing the notarized signature of the claimant confirming that she or he has acquired said ownership, has read and agrees to be bound by these Terms of Service; or, ii) Brain Host is served with a valid order of a court, agency, or appropriate internet controlling entity such as Internt Corporation for Assigned Names and Numbers ("ICANN"), requiring Brain Host (or affiliate) to transfer such ownership to said claimant.</p>
<p>Subscriber acknowledges and accepts that the foregoing policies and procedures regarding transfer of ownership are the only way that notice(s) can be given and changes can be effected regarding said transfer of ownership within Brain Host; and, further, that any other changes made directly by Subscriber or by others within the online records of Brain Host or of its affiliates shall not be deemed effective to give notice to Brain Host or its affiliates of any changes in said ownership.</p>
<p>E. Disputing Site or Account Ownership Disputes sometimes arise between or among multiple persons claiming ownership of or rights in a site hosted by Brain Host or in an associated Brain Host account. Brain Host is not obligated to resolve any such disputes. If multiple persons are claiming ownership of or rights in a site hosted by Brain Host or in an associated Brain Host account, and, in Brain Host\'s sole judgment, there is not certainty as to the ownership of or rights in said site or account, then Brain Host will, to the extent of its knowledge and ability, notify said persons of the dispute and demand that said persons promptly, conclusively, and finally resolve the dispute in a manner which makes clear who the owner(s) and/or interest holder(s) is/are and in a manner which relieves Brain Host of all liability or obligations concerning the dispute. If the disputing persons fail so to resolve the dispute within what Brain Host, in its sole judgment, deems to be a reasonable time, then Brain Host, at its option and without any obligation to do so, may, in accordance with and subject to the laws of the State of Ohio, file an interpleader action in a court of competent jurisdiction within the State of Ohio for the purpose of allowing the contending persons to resolve said dispute and to reach certainty regarding ownership of or rights in said site and/or account. The person or persons conclusively and finally determined by the interpleader action to be the rightful owner(s) or interest holder(s) of said site and/or associated account shall be obligated to reimburse Brain Host for all of its expenses relative to said interpleader action including without limit all its court costs and reasonable attorney fees. All amounts owed to Brain Host under this section 5.03 shall be deemed due and payable immediately upon thirty (30) days after judgment or settlement is reached.</p>
<p><strong>VII. PRIVACY POLICY </strong></p>
<p>A. Commitment. The Brain Host commitment to our Subscribers\' privacy is set forth in this section. Except as required by law or as otherwise provided herein, Brain Host will take commercially reasonable steps to ensure your right to privacy. Brain Host is committed to developing long lasting relationships that are built on trust and will never intentionally violate that trust.</p>
<p>B. Encryption. When Subscriber orders from Brain Host, Personal Data Transmissions are encrypted. When Subscriber orders from Brain Host, all of Subscriber\'s personal information is protected. Brain Host uses Secure Sockets Layer (SSL), the industry standard, for encrypting all personal information, including name, address and credit card numbers.</p>
<p>C. Confidentiality. With the exception of trusted business affiliates and/or associates who work on behalf of or in connection with Brain Host, subject to specific confidentiality agreements, Brain Host will not provide or sell to any third party your personal information and will keep all Subscriber information confidential, subject to the following:</p>
<p>Upon registration, certain Subscriber information is transferred to WHOIS (domain registration information), to our affiliated third-party registrar, FastDomain, to Postini (email addresses), and to Comodo (SSL cert. creation).</p>
<p>Brain Host will respond to subpoenas, court orders, or other legal process, and will utilize Subscriber information as necessary to establish or exercise Brain Host\'s legal rights or defend against legal claims. Brain Host will charge the person or entity for submitting a civil subpoena for costs associated with subpoena compliance. Payment must be made within thirty (30) days from the date of receipt of the Brain Host invoice. Checks should be made out to Brain Host. Brain Host\'s subpoena compliance costs are as follows: Research-$150.00/hour; Federal Express-Cost as Billed; Copies-$1.00/page; Compact Discs &#8211; $10.00/per CD.</p>
<p>Brain Host will share information to investigate, prevent, or take action regarding illegal activities, suspected fraud, situations involving potential threats to the physical safety of any person, violations or suspected violations of these Terms, or as otherwise required by law.</p>
<p>When we are threatened with suit by a third party, or any other legal action brought to our attention involving us based on the anonymity of the domain, we may seek assurance from you the customer concerning your promise to indemnify us and written notice that you have contacted the plaintiff or representative for the complainant and made your contact information available to them. Failure to provide those assurances may be considered by us to be a breach of your Agreement and may result in deactivation of your domain name and forfeit the right to privacy on a domain. A pro-rated refund will be issued to the payment method on file for the remaining unused service.</p>
<p><strong>VIII. RIGHT TO CONTACT REGARDING POTENTIAL CUSTOMER REVIEW</strong></p>
<ol>
<li> If, as a Brain Host subscriber, you give a review of Brain Host services, whether by phone, social media or email, you<strong> </strong>agree to grant Brain Host a non-exclusive, worldwide, royalty-free license to use the words of your review in any media or technology and have these words attributed to you.<strong></strong></li>
</ol>
<p><strong>IX. YOUR CONSENT TO RECEIVE COMMERCIAL EMAIL FROM BRAIN HOST, LLC</strong></p>
<ol>
<li> By registering an account with BrainHost.com, you consent to receive, from time to time, commercial electronic messages from us which may include offers from us, our affiliates, partners and third parties advertising our products. If you do not wish to receive advertisements from us or partners, please contact us at <a href="mailto:support@brainhost.com">support@brainhost.com</a>. To unsubscribe from the mailing lists of third-party advertisers, the relevant opt-out procedure must be followed for each third party advertiser. Opting out of a particular third party advertiser will not prevent other third-party advertisers or Brain Host partners from sending you advertisements.<strong></strong></li>
</ol>
<p><strong>X. "UNLIMITED" USAGE POLICIES AND DEFINITIONS </strong></p>
<p>A. What "Unlimited" means. Brain Host does not set an arbitrary limit or cap on the amount of resources a single Subscriber can use. In good faith and subject to these Terms, Brain Host makes every commercially reasonable effort to provide its Subscribers with all the storage and bandwidth resources needed to power their web sites successfully, as long as the Subscriber\'s use of the service complies with these Terms. By not setting limits on key resources, we are able to provide simple, consistent pricing to our Subscribers as they grow their websites. As a result, a typical website may experience periods of great popularity and resulting increased storage without experiencing any associated increase in hosting charges.</p>
<p>B. What "Unlimited" DOES NOT mean. Brain Host employs complex mechanisms to protect its Subscribers and systems from abuse. Brain Host\'s offering of "unlimited" services is not intended to allow the actions of a single or few Subscribers to unfairly or adversely impact the experience of other Subscribers.<br /> Brain Host\'s service is a shared hosting service, which means that multiple Subscriber web sites are hosted from the same server and share server resources. Brain Host\'s service is designed to meet the typical needs of small business and home business website Subscribers in the United States. It is NOT intended to support the sustained demand of large enterprises, internationally based businesses, or non-typical applications better suited to a dedicated server.<br /> Brain Host will make every commercially reasonable effort to provide additional resources to Subscribers who are using their website(s) consistent with these Terms, including moving Subscribers to newer and bigger shared servers as necessary. However, in order to ensure a consistent and quality experience for all Subscribers, Brain Host does place automated safeguards to protect against any one site growing too quickly and adversely impacting the system until Brain Host can evaluate said sites resource needs.</p>
<p>C. Unlimited Hosting Space; excessive MySQL files. Brain Host does not set arbitrary limits on the amount of disk space a Subscriber can use for the Subscriber\'s website, nor does Brain Host charge additional fees based on an increased amount of storage used, provided the Subscriber\'s use of storage complies with these Terms. Please note, however, that the Brain Host service is designed to host websites. Brain Host does NOT provide unlimited space for online storage, backups, or archiving of electronic files, documents, log files, etc., and any such prohibited use of the Services will result in the termination of Subscriber\'s account, with or without notice. Accounts with a large number of files (inode count in excess of 200,000) can have an adverse affect on server performance. Similarly, accounts with an excessive number of MySQL/PostgreSQL tables (i.e., in excess of 1000 database tables) or of database size (i.e., in excess of 3GB total MySQL/PostgreSQL usage or 2GB MySQL/PostgreSQL usage in a single database) negatively affect the performance of the server. Brain Host may request that the number of files/inodes, database tables, or total database usage be reduced to ensure proper performance or may terminate the Subscriber\'s account, with or without notice.</p>
<p>D. Unlimited File Transfer. Brain Host does not set arbitrary limits on the amount of visitor traffic a web site can receive or on the amount of content a Subscriber can upload to his/her/its website in a given month, nor does Brain Host charge additional fees based on increased use of bandwidth, as long as the Subscriber\'s use of the Services complies with these Terms. In most cases, a Subscriber\'s web site will be able to support as much traffic as the Subscriber can legitimately acquire. However, Brain Host reserves the right to limit processor time, bandwidth, processes, or memory in cases where it is necessary to prevent negatively impacting other Subscribers.</p>
<p>E. Unlimited Domain Hosting. Brain Host does not set arbitrary limits on the number of domain names a Subscriber can associate with the Subscriber\'s web hosting account.</p>
<p><strong>XI. COOKIE POLICY STATEMENT </strong></p>
<p>A. General Purposes. Brain Host understands that many of its Subscribers are concerned about "cookies", which are electronic collections of information stored on the local computer of a person using the worldwide web and which are used chiefly by websites to keep track of visitors and registered users and to relate one computer transaction to a later one. Brain Host provides this Cookie Policy Statement to let you, the Subscriber, know how Brain Host uses this technology. Brain Host uses cookies to help Brain Host improve its website and web hosting services, and, most importantly, to provide Brain Host\'s existing Subscribers with the opportunity for continued savings and increased convenience.</p>
<p>B. Cookies for Improving Our Web Site. Brain Host uses cookies to inform Brain Host of a repeat visit. The cookie does not tell Brain Host who a visitor is, the visitor\'s name, email address, or Passwords.</p>
<p>C. Cookies for Banner Rewards Program. To offer Brain Host Subscribers continued savings, Brain Host uses cookies to help monitor the traffic generated from Brain Host banners and logo buttons displayed on Brain Host Subscribers\' websites.</p>
<p>D. Cookies for Subscriber Account Management. For Brain Host Subscribers, Brain Host uses cookies to store user names for added convenience to the Webmaster. As part of our Brain Host web hosting package, Brain Host offers password-protected, web-based management tools. By storing a Subscriber\'s username in a cookie, the Webmaster will not have to fill out form fields each time he or she manages the account. (The cookie does not store Passwords.) Brain Host is dedicated to using the newest technologies in order to simplify our Subscribers\' experience.</p>
<p><strong>XII. PROHIBITED USES </strong></p>
<p>A. Breach of Terms and Account Termination. The uses of Brain Host Services set forth in this section 9 herein below are prohibited. The engaging in any prohibited use as set forth herein by Subscriber or by any affiliate or subscriber of Subscriber ( as determined in the sole discretion of Brain Host) constitutes a material breach of these Terms and will subject Subscriber\'s account to immediate termination without notice and without any refund.</p>
<p>B. Spamming. Spamming, whether or not it overloads the Services or disrupts service to Brain Host\'s Subscribers, is prohibited. The term "Spamming" includes, but is not limited to, the sending of unsolicited bulk and/or commercial messages over the Internet, maintaining an open SMTP policy, or sending to any mailing list that is not double opt in. Brain Host requires that all email messages contain an automated opt out . We do not allow purchased lists. Brain Host\'s Subscribers are required to follow all rules in the Can Spam Act (<a href="http://www.ftc.gov/bcp/edu/pubs/business/ecommerce/bus61.shtm" onclick="javascript:_gaq.push([\'_trackEvent\',\'outbound-article\',\'http://www.ftc.gov\']);">http://www.ftc.gov/bcp/edu/pubs/business/ecommerce/bus61.shtm</a>) as well as our company spam rules. Brain Host reserves the right to determine, in its sole and absolute discretion, whether e-mail recipients were part of an opt-in email list. Irrespective of whether an email campaign constitutes Spamming as defined herein, Brain Host allows a MAXIMUM of 500 emails per hour to be sent from any individual hosting account.</p>
<p>C. Prohibited Offerings. No Subscriber may utilize the Services to provide, sell or offer to sell the following: controlled substances; illegal drugs and drug contraband; weapons; pirated materials; instructions on making, assembling or obtaining illegal goods or weapons to attack others; information used to violate the copyright(s) of, violate the trademark(s) of or to destroy others\' intellectual property or information; information used to illegally harm any people or animals; pornography, nudity, sexual products, programs or services; escort services or other content deemed adult related.</p>
<p>D. Profanity. Profanity or profane subject matter in the site content and in the domain name are prohibited.</p>
<p>E. Private Information and Images. Subscribers may not post or disclose any personal or private information about or images of children or any third party without the consent of said party (or a parent\'s consent in the case of a minor).</p>
<p>F. Violations of Intellectual Property Rights. Any violation of any person\'s or entity\'s intellectual property rights, rights of privacy, rights of publicity or other personal rights is prohibited. Brain Host is required by law to remove or block access to content appearing on or through the Services upon receipt of proper notice of copyright infringement (see "Copyright Infringement Notice Information" below).</p>
<p>G. Misrepresentation of Transmission Information. Forging, misrepresenting, omitting, or deleting message headers, return mailing information and/or Internet protocol addresses to conceal or misidentify the origin of a message is prohibited.</p>
<p>H. Viruses and Other Destructive Activities. Use of the Services for creating or sending Internet viruses, worms or Trojan horses, or for pinging, flooding or mail bombing, or engaging in denial of service attacks is prohibited. It is also prohibited for any Subscriber to engage in other activity that is intended to disrupt or interfere with, or that results in the disruption of or interference with, the ability of others to effectively use the Services (or any connected network, system, service or equipment) or conduct their business over the Internet.</p>
<p>I. Hacking. "Hacking" and related activities are prohibited. "Hacking" includes, but is not limited to, the following activities: illegally or without authorization, accessing computers, accounts or networks, penetrating or attempting to penetrate security measures, port scans, stealth scans, and other activities designed to assist in hacking.</p>
<p>J. Anonymous Proxies. Brain Host does not allow the use of anonymous proxy scripts on its servers. They can be very abusive to the server resources, affecting all users on that server.</p>
<p>K. Export Control Violations. The exportation of encryption software outside of the United States and/or violations of United States law relating to the exportation of software is prohibited. Subscriber may not export or transfer, directly or indirectly, any regulated product or information to anyone outside the United States without complying with all applicable statues, codes, ordnances, regulations, and rules imposed by U.S. federal, state or local law, or by any other applicable law.</p>
<p>L. Child Pornography. The use of the Services to store, post, display, transmit, advertise or otherwise make available child pornography is prohibited. Brain Host is required by law to, and will, notify law enforcement agencies when it becomes aware of the presence of child pornography on, or being transmitted through, the Services.</p>
<p>M. Other Illegal Activities. The use of the Services to engage in any activity that is determined by Brain Host, in its sole and absolute discretion, to be illegal is prohibited. Such illegal activities include, but are not limited to, storing, posting, displaying, transmitting or otherwise making available ponzi or pyramid schemes, fraudulently charging credit cards or displaying credit card information of third parties without their consent, and failure to comply with applicable on-line privacy laws. Brain Host will cooperate fully with appropriate law enforcement agencies in connection with any and all illegal activities occurring on or through the Services.</p>
<p>N. Obscene, Defamatory, Abusive or Threatening Language. Use of the Services to store, post, transmit, display or otherwise make available obscene, defamatory, harassing, abusive or threatening language is prohibited.</p>
<p>O. BACKUP STORAGE. BRAIN HOST OFFERS ITS SERVICES TO HOST WEB SITES, NOT TO STORE DATA. USING AN ACCOUNT AS AN ONLINE STORAGE SPACE FOR ARCHIVING ELECTRONIC FILES IS PROHIBITED AND WILL RESULT IN TERMINATION OF HOSTING SERVICES WITHOUT PRIOR NOTICE.</p>
<p>P. Other Activities. Engaging in any activity that, in Brain Host\'s sole and absolute discretion, disrupts, interferes with or is harmful to (or threatens to disrupt, interfere with, or be harmful to) the Services, Brain Host\'s business, operations, reputation, goodwill, Subscribers and/or Subscriber relations, or the ability of Brain Host\'s Subscribers to effectively use the Services is prohibited. Such prohibited activities include making available any program, product or service that is designed to or could be used to violate these Terms. In addition, the failure of Subscriber to cooperate with Brain Host in correcting or preventing violations of these Terms by, or that result from the activity of, a subscriber, patron, customer, invitee, visitor, or guest of the Subscriber constitutes a violation of these Terms by Subscriber.</p>
<p><strong>XIII. COPYRIGHT, TRADEMARK, AND "IP RIGHTS HOLDER" NOTICE OF INFRINGEMENT INFORMATION</strong></p>
<p>A. In accordance with the Digital Millennium Copyright Act, Brain Host has adopted a policy that provides for termination of websites hosted by Brain Host that are found to infringe on copyrights, trademarks or other intellectual property rights of third parties (each an €œIP Rights Holder€) If a IP Rights Holder holder believes that there has been a violation of his or her copyright on a website that is hosted by Brain Host or a Brain Host subsidiary, and the IP Rights Holder wants Brain Host to remove the website or disable the material in question, Brain Host will remove the website or disable the material if the IP Rights Holder provides us with all of the following information.</p>
<p>B. A signature of a person authorized to act on behalf of the owner of the exclusive right that is allegedly infringed. Identification of the copyrighted work that is claimed is being infringed, or, in the case of claimed infringement of multiple copyrighted works, a representative list of such works.</p>
<p>C. Identification of the material that is claimed to be infringing or is the subject of infringing activity and that should be removed or access to which should be disabled, with information reasonably sufficient to permit us to locate the material.</p>
<p>D. Information reasonably sufficient to permit us to contact the person giving the notification, such as an address and telephone, and, if available, an electronic mail address at which such person may be contacted.</p>
<p>E. A statement that the person giving the notification has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law.</p>
<p>F. A statement that the information in the notification is accurate, and under penalty of perjury, that the person giving the notification is authorized to act on behalf of the owner of the exclusive right that is allegedly infringed. Email DMCA reports to legal@BrainHost.com.</p>
<p>G. IMPORTANT NOTE: IN THE EVENT YOU SEND US A NOTICE OF ANY KIND VIA EMAIL AND DO NOT RECEIVE A RESPONSE FROM US, PLEASE SUBMIT A DUPLICATE COPY VIA PAPER (4000 Embassy Parkway, Suite 120, Akron, OH 44333) AND/OR FAX (FAX #330-666-2521). DUE TO THE VAGARIES OF THE INTERNET, AND EMAIL COMMUNICATION IN PARTICULAR, INCLUDING WITHOUT LIMITATION THE BURDENS OF SPAM AND THE OCCASIONAL, UNINTENDED EFFECTS OF SPAM FILTERS, SENDING AN ALTERNATE FORM OF NOTICE (VIA PAPER AND/OR FAX), WILL HELP ASSURE THAT YOUR NOTICE WILL BE RECEIVED BY US AND ACTED ON IN A TIMELY MANNER.</p>
<p><strong>XIV. GENERAL </strong></p>
<p>A. Promotional Pricing. Brain Host may periodically offer "free" or discounted services or credits in connection with a promotional offer, including, without limitation, free domain name registration. Such promotional offers are honored only in connection with the specific promotional package to which they apply. In the event a Subscriber downgrades or otherwise changes his/her/its subscription to a subscription to which a promotional offer does not apply, Subscriber will forfeit any unused free credits offered under the promotional packaged and Brain Host will charge Subscriber the prevailing fees for any free credits redeemed by Subscriber under the promotional package.</p>
<p>B. Backups. For its own operational efficiencies and purposes, Brain Host from time to time backs up data on its servers, but is under no obligation or duty to Subscriber to do so under these Terms. IT IS SOLELY SUBSCRIBER\'S DUTY AND RESPONSIBILITY TO BACKUP SUBSCRIBER\'S FILES AND DATA ON BRAIN HOST SERVERS, AND under no circumstance will Brain Host be liable to anyone FOR DAMAGES OF ANY KIND under any legal theory for loss of Subscriber FILES AND/or data on any Brain Host server. Brain Host will not attempt to back up accounts that exceed 50,000 files or 30 Gigs of space for any reason.</p>
<p>C. Monitoring and Disclosures. All activities occurring on, in, and/or via the Services or any website hosted by Brain Host may be monitored, recorded, and examined by any authorized person, including as well law enforcement. In general, Brain Host does not monitor its Subscribers\' websites or activities to determine whether they are in compliance with these Terms. However, when and if Brain Host becomes aware of any violation of these Terms, Brain Host may take any lawful action, and in the event of illegal activity, will take action, to stop or correct such violation, including, but not limited to, shutting down a website, denying access to the Services or to the Internet via Brain Host, and/or removing non-complying information. In addition, Brain Host may take any lawful action against a Subscriber or a subscriber, patron, customer, invitee, visitor, or guest of such Subscriber because of the activities of such subscriber, patron, customer, invitee, visitor, or guest. Brain Host reserves the right to take any such action even though such action may affect other subscribers, patrons, customers, invitees, visitors, or guests of the Subscriber. Brain Host may disclose any information in its possession, including, without limitation, information about Subscribers, internet transmissions and website activity in order to comply with a court order, subpoena, summons, discovery request, warrant, statute, regulation, governmental request, or other legal process to protect Brain Host or others from harm, and/or to ensure the proper operation of the Services. BrainHost.com has no obligation to notify any person, including the Subscriber about whom information is sought, that Brain Host has provided the information.</p>
<p>D. Accurate Account Information. Subscriber must continually update and keep accurate and current Subscriber\'s contact information stored and saved on Brain Host in order to avoid termination of Subscriber\'s Brain Host account(s).</p>
<p>E. Duty to Notify Brain Host of Breach. If Subscriber discovers anyone on the Brain Host system violating any of these Terms or notices anything suspicious from the Brain Host network, Subscriber agrees to report the violation or suspicious activity to tos@BrainHost.com for investigation. Brain Host reserves the right to and will immediately terminate any account which Brain Host concludes to be in violation of any of these Terms.</p>
<p>F. Reservation of Rights. Brain Host reserves the right to refuse or to cancel service to any prospective Subscriber or existing Subscriber for any lawful reason at any time during Subscriber\'s hosting term with Brain Host.</p>
<p>G. Severability. These Terms are binding upon Brain Host, all existing and prospective Subscribers, and upon the assigns, heirs, and successors of each. If any provision of these Terms is held by any court of competent jurisdiction to be invalid or otherwise unenforceable, the rest of these Terms shall, nevertheless, continue to be valid and in full force and effect, to the extent said remaining Terms are then otherwise consistent with the original intent of the Terms of Service.</p>
<p>H. Governing Law. These Terms shall be governed by the laws of the State of Ohio without reference to conflict of law principles. The United Nations Convention on the International Sale of Goods shall not apply and is hereby expressly excluded. By subscribing to or using any of the Services of Brain Host, Subscriber agrees that all disputes, if any, involving Brain Host shall be subject exclusively to the jurisdiction of the State and Federal Courts within the State of Ohio; provided, further, that all action brought against Brain Host in State Court must be brought in Summit County, Ohio and, if in Federal Court, in Summit County, Ohio. Subscriber hereby agrees that it is subject to the in personam jurisdiction of said courts for all purposes in connection with these Terms and/or in connection with any claim or dispute involving Brain Host. Subscriber hereby waives any and all objections that it has or might have, known or unknown, whether under Ohio\'s long arm statute or otherwise, to the existence of said in personam jurisdiction. Subscriber agrees that it has no right to and shall not file or otherwise bring a lawsuit against Brain Host outside the State of Ohio; and, that Subscriber, if involved before a court in a lawsuit outside of the State of Ohio, shall be deemed to support and to stipulate to a motion made by Brain Host to dismiss said lawsuit with respect to Brain Host.</p>
<p>I. Parked Page Services. Brain Host provides Parked Page Services on domains registered through or hosted with Brain Host. User can opt out of the Parked Page Services at any time by simply replacing the default web page on the parked domain or pointing the DNS away from Brain Host. By using any of the Parked Pages Services, User agrees that Brain Host may point the domain name or DNS to one of Brain Host\'s or Brain Host\'s affiliates web pages, and that they may place advertising on User\'s web page and that Brain Host specifically reserves this right. User shall have no right to any compensation and shall not be entitled and shall have no right to receive any funds related to the monetization of User\'s Parked Pages. User agrees to indemnify and hold harmless Brain Host for any complications arising out of use of the Parked Page Services, including, but not limited to, actions Brain Host chooses to take to remedy User\'s improper or illegal use of a Web site hosted by Brain Host. User agrees it is not entitled to a refund of any fees paid to Brain Host. If a dispute arises as a result of one or more of User\'s Parked Pages, User will indemnify, defend and hold Brain Host harmless for damages arising out of such dispute. User also agrees that if Brain Host is notified that a complaint has been filed with a governmental, administrative or judicial body, regarding a Web site hosted by Brain Host that Brain Host, in its sole discretion, may take whatever action Brain Host deems necessary regarding further modification, assignment of and/or control of the Web site to comply with the actions or requirements of the governmental, administrative or judicial body until such time as the dispute is settled.</p>
<p><strong>XV. WARRANTY DISCLAIMER &#8211; LIMITATIONS &#8211; INDEMNIFICATION </strong></p>
<p>A. Warranty Disclaimer. YOU, THE SUBSCRIBER, ACKNOWLEDGE THAT THE SERVICES AND THE SOFTWARE ARE PROVIDED "AS IS, AS AVAILABLE" WITHOUT ANY WARRANTY OF ANY KIND. BRAIN HOST HEREBY DISCLAIMS ANY WARRANTY OR CONDITION WITH RESPECT TO THE QUALITY, PERFORMANCE OR FUNCTIONALITY OF THE SERVICES AND SOFTWARE, OR WITH RESPECT TO THE QUALITY OR ACCURACY OF ANY INFORMATION OBTAINED FROM OR AVAILABLE THROUGH USE OF THE SERVICES AND SOFTWARE, OR THAT THE SERVICES AND SOFTWARE WILL BE UNINTERRUPTED, ERROR-FREE OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. THE SERVICES AND SOFTWARE MAY CONTAIN ERRORS. NO ADVICE OR INFORMATION GIVEN BY BRAIN HOST OR BRAIN HOST\'S REPRESENTATIVES INCLUDING, WITHOUT LIMITATION, SUBSCRIBER SUPPORT REPRESENTATIVES, SHALL CREATE A WARRANTY. BRAIN HOST DISCLAIMS ALL WARRANTIES OR CONDITIONS, EXPRESS, IMPLIED OR STATUTORY INCLUDING, WITHOUT LIMITATION, WARRANTIES OR CONDITIONS OF QUIET ENJOYMENT AND NON-INFRINGEMENT AND ANY IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY, TITLE, FITNESS FOR A PARTICULAR PURPOSE, MERCHANTABILITY OF COMPUTER PROGRAMS AND CONTENT. BRAIN HOST DOES NOT GUARANTEE THAT USERS WILL BE ABLE TO USE THE SERVICES AT TIMES OR LOCATIONS OF THEIR CHOOSING. BRAIN HOST DOES NOT WARRANT THAT THE SERVICES ARE COMPATIBLE WITH ANY THIRD PARTY SERVICE OR SOFTWARE, EVEN IF SUCH THIRD PARTY CLAIMS, REPRESENTS OR WARRANTS THAT SUCH SERVICE OR SOFTWARE IS COMPATIBLE WITH ANY SERVICE OR BRAIN HOST IN PARTICULAR.</p>
<p>B. Limitations on Brain Host\'s Liability. BRAIN HOST SHALL NOT BE LIABLE FOR NONPERFORMANCE OR DELAY IN PERFORMANCE CAUSED BY ANY REASON, WHETHER WITHIN OR OUTSIDE OF ITS CONTROL. IN NO EVENT SHALL BRAIN HOST BE LIABLE UNDER CONTRACT, NEGLIGENCE, TORT, CONVERSION, COPYRIGHT INFRINGEMENT, TRADEMARK INFRINGEMENT, IP RIGHTS HOLDER INFRINGEMENT, STRICT LIABILITY OR ANY OTHER LEGAL OR EQUITABLE THEORY FOR ANY DIRECT, INDIRECT, INCIDENTAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING, WITHOUT LIMITATION, LOSS OF USE, LOST PROFITS, LOSS OF DATA OR INFORMATION OF ANY KIND OR LOSS OF BUSINESS GOODWILL OR OPPORTUNITY) WHETHER OR NOT BRAIN HOST HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH LOSS OR DAMAGES. BRAIN HOST SHALL NOT BE LIABLE FOR THE COST OF PROCUREMENT OF SUBSTITUTE GOODS, SERVICES OR TECHNOLOGY. BRAIN HOST\'S ENTIRE LIABILITY AND SUBSCRIBER\'S EXCLUSIVE REMEDY WITH RESPECT TO ANY USE OF THE SERVICES IS THE CANCELLATION OF SUBSCRIBER\'S ACCOUNT AS SET FORTH HEREIN. IN NO EVENT SHALL BRAIN HOST\'S LIABILITY TO YOU, THE SUBSCRIBER, EXCEED THE GREATER OF ONE DOLLAR ($1.00) OR ANY AMOUNTS ACTUALLY PAID IN CASH BY YOU, THE SUBSCRIBER, TO BRAIN HOST FOR THE PRIOR ONE MONTH PERIOD. NO ACTION, REGARDLESS OF FORM, ARISING OUT OF THESE TERMS OR OUT OF THE SERVICES MAY BE BROUGHT BY YOU, THE SUBSCRIBER, MORE THAN ONE YEAR AFTER THE EVENT WHICH GAVE RISE TO THE CAUSE OF ACTION . SOME JURISDICTIONS DO NOT ALLOW A LIMITATION ON LIABILITY FOR NEGLIGENCE THAT CAUSES DEATH OR PERSONAL INJURY AND, IN SUCH JURISDICTIONS, BRAIN HOST\'S LIABILITY SHALL BE LIMITED TO THE GREATEST EXTENT PERMITTED BY LAW.</p>
<p>C. Indemnification of Brain Host. You, the Subscriber, agree to defend, indemnify and hold Brain Host, its affiliates and its sponsors, partners, other co-branders and the respective directors, officers and employees of each harmless from and against any and all claims, losses, damages, liabilities and costs (including, without limitation, reasonable attorneys\' fees and court costs) arising out of or relating to your breach of any of these Terms or use by you or any third party of the Services, except to the extent the foregoing directly result from Brain Host\'s own gross negligence or willful misconduct. Brain Host reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, the Subscriber.</p>
<p><strong>XVI. PROHIBITED PERSONS (COUNTRIES, ENTITIES, AND INDIVIDUALS) </strong></p>
<p>A. Sanctioned Countries. The government of the United States of America, through various of its offices and agencies, including but not limited to, through one or more Executive Orders of the President of the United States, through rules and regulations of the United States Department of State, Department of the Treasury, and Department of Commerce, has determined that, with respect to all or certain commercial activities that would otherwise occur between i) the United States, its citizens or residents on the one hand and ii) the governments, citizens, or residents of certain other countries ("Sanctioned Countries") on the other hand, said commercial activities are to be prohibited, embargoed, sanctioned, banned, and/or otherwise excluded. "Sanctioned Countries" shall be deemed automatically to be added to or otherwise modified from time to time consistent with the determination(s) of the government of the United States, and shall include all other countries with respect to which commercial activities are prohibited, embargoed, sanctioned, banned and/or otherwise excluded by determination(s) of the government of the United States from time to time.</p>
<p>Each Sanctioned Country, all governmental, commercial, or other entities located therein, and all individuals located in any Sanctioned Country are hereby prohibited from registering or signing up with, subscribing to, or using any service of Brain Host.</p>
<p>Each individual which is a National or Citizen of a Sanctioned Country is hereby prohibited from registering or signing up with, subscribing to, or using any service of Brain Host, regardless of where said individual is located.</p>
<p>B. Prohibited Organizations/Entities. The government of the United States of America, through various of its offices and agencies, including but not limited to, through one or more Executive Orders of the President of the United States, through rules and regulations of the United States Department of State, Department of the Treasury, and Department of Commerce, has determined that certain organizations and/or entities (collectively "Prohibited Organizations/Entities" and individually "Prohibited Organization/Entity") are to be prohibited, embargoed, sanctioned, banned, and/or otherwise excluded from all or certain commercial transactions with the United States, its citizens and residents. The Prohibited Organizations/Entities are those as set forth in the applicable records of the government of the United States, including without limit those set forth at: <a href="http://www.ustreas.gov/ofac" onclick="javascript:_gaq.push([\'_trackEvent\',\'outbound-article\',\'http://www.ustreas.gov\']);">http://www.ustreas.gov/ofac</a>; and, <a href="http://www.treasury.gov/resource-center/sanctions/SDN-List/Pages/default.aspx" onclick="javascript:_gaq.push([\'_trackEvent\',\'outbound-article\',\'http://www.treasury.gov\']);">http://www.treasury.gov/resource-center/sanctions/SDN-List/Pages/default.aspx</a>, as said determinations and resulting records may be amended, updated, or otherwise modified from time to time.</p>
<p>Each Prohibited Organization/Entity is hereby prohibited from registering or signing up with, subscribing to, or using any service of Brain Host.</p>
<p>C. Prohibited Individuals. The government of the United States of America, through various of its offices and agencies, including but not limited to, through one or more Executive Orders of the President of the United States, through rules and regulations of the United States Department of State, Department of the Treasury, and Department of Commerce, has determined that certain individuals (collectively "Prohibited Individuals" and individually "Prohibited Individual"), including without limit, certain Specially Designated Nationals are to be prohibited, embargoed, sanctioned, banned, and/or otherwise excluded from all or certain commercial transactions with the United States, its citizens and residents. The Prohibited Individuals are those as set forth in the applicable records of the government of the United States, including without limit those set forth at: <a href="http://www.ustreas.gov/ofac" onclick="javascript:_gaq.push([\'_trackEvent\',\'outbound-article\',\'http://www.ustreas.gov\']);">http://www.ustreas.gov/ofac</a>; and, <a href="http://www.treasury.gov/resource-center/sanctions/SDN-List/Pages/default.aspx" onclick="javascript:_gaq.push([\'_trackEvent\',\'outbound-article\',\'http://www.treasury.gov\']);">http://www.treasury.gov/resource-center/sanctions/SDN-List/Pages/default.aspx</a>, as said determinations and resulting records may be amended, updated, or otherwise modified from time to time.</p>
<p>Each Prohibited Individual is hereby prohibited from registering or signing up with, subscribing to, or using any service of Brain Host.</p>
<p>IF YOU, FOR YOURSELF OR ON BEHALF OF ONE OR MORE PERSONS YOU ARE REPRESENTING WITH RESPECT TO BRAIN HOST SERVICES, DO NOT AGREE TO ANY OF THE FOREGOING TERMS, YOU MUST, FOR YOURSELF AND ON BEHALF ANY SUCH PERSON(S), DISCONTINUE THE REGISTRATION PROCESS, DISCONTINUE YOUR USE OF THE SERVICES, AND, IF YOU ARE ALREADY A MEMBER, CANCEL YOUR BRAIN HOST ACCOUNT. BEGINNING NOW, ANY CONTINUATION BY YOU IN USING THE SERVICES CONSTITUTES FOR YOU AND THOSE REPRESENTED BY YOU AN EXPRESS AFFIRMATION AND COMMITMENT TO BE (OR TO CONTINUE TO BE, AS APPLICABLE) LEGALLY BOUND BY AND TO COMPLY WITH ALL OF THESE TERMS.</p>
';