		<div id="t-main" role="main">
			<div class="center-width">
				<div class="">
					<h2 style="text-align:left;">Privacy Policy</h2>
					<p><strong>A. Commitment.</strong> The Hosting Account Setup commitment to our Subscribers&#8217; privacy is set forth in this section. Except as required by law or as otherwise provided herein, Hosting Account Setup will take commercially reasonable steps to ensure your right to privacy. Hosting Account Setup is committed to developing long lasting relationships that are built on trust and will never intentionally violate that trust.</p>
					<p><strong>B. Encryption.</strong> When Subscriber orders from Hosting Account Setup, Personal Data Transmissions are encrypted. When Subscriber orders from Hosting Account Setup, all of Subscriber&#8217;s personal information is protected. Hosting Account Setup uses Secure Sockets Layer (SSL), the industry standard, for encrypting all personal information, including name, address and credit card numbers.</p>
					<p><strong>C. Confidentiality.</strong> With the exception of trusted business affiliates and/or associates who work on behalf of or in connection with Hosting Account Setup, subject to specific confidentiality agreements, Hosting Account Setup will not provide or sell to any third party your personal information and will keep all Subscriber information confidential,</p>
					<p><strong>subject to the following:</strong></p>
					<p style="padding-left: 30px;">Upon registration, certain Subscriber information is transferred to WHOIS (domain registration information), to our affiliated third-party registrar, FastDomain, to Postini (email addresses), and to Comodo (SSL cert. creation).</p>
					<p style="padding-left: 30px;">Hosting Account Setup will respond to subpoenas, court orders, or other legal process, and will utilize Subscriber information as necessary to establish or exercise Hosting Account Setup&#8217;s legal rights or defend against legal claims. Hosting Account Setup will charge the person or entity for submitting a civil subpoena for costs associated with subpoena compliance. Payment must be made within thirty (30) days from the date of receipt of the Hosting Account Setup invoice. Checks should be made out to Hosting Account Setup. Hosting Account Setup&#8217;s subpoena compliance costs are as follows: Research-$150.00/hour; Federal Express-Cost as Billed; Copies-$1.00/page; Compact Discs &#8211; $10.00/per CD.</p>
					<p style="padding-left: 30px;">Hosting Account Setup will share information to investigate, prevent, or take action regarding illegal activities, suspected fraud, situations involving potential threats to the physical safety of any person, violations or suspected violations of these Terms, or as otherwise required by law.</p>
					<p style="padding-left: 30px;">When we are threatened with suit by a third party, or any other legal action brought to our attention involving us based on the anonymity of the domain, we may seek assurance from you the customer concerning your promise to indemnify us and written notice that you have contacted the plaintiff or representative for the complainant and made your contact information available to them. Failure to provide those assurances may be considered by us to be a breach of your Agreement and may result in deactivation of your domain name and forfeit the right to privacy on a domain. A pro-rated refund will be issued to the payment method on file for the remaining unused service.</p>
				</div>
			</div>
		</div>